#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
if [ -f "$SCRIPT_DIR/aves" ]; then
    "$SCRIPT_DIR/aves" --install
     echo "aves has been created in Application/Office and in Application/Graphics"	
elif [ -f "$SCRIPT_DIR/aview" ]; then
	"$SCRIPT_DIR/aview" --install
 echo "aview has been created in Application/Office and in Application/Graphics"	
elif [ -f "$SCRIPT_DIR/asmo-re" ]; then
	"$SCRIPT_DIR/asmo-re" --install
 echo "asmo-re has been created in Application/Office"	
else 
	echo "None of the next files \"asmo-re, aves, aview\" has been found!"
fi